export const COMPANY_INFO = {
  name: '慶宗塑膠有限公司',
  nameEn: 'CHIN TZON Plastics Co., Ltd.',
  shortName: '慶宗塑膠',
  description: '慶宗塑膠有限公司成立於1977年，近50年專業塑膠製品製造經驗。專營塑膠袋、塑膠膜、塑膠繩、塑膠網等產品，提供客製化生產、批發代工服務。',
  phone: '05-2211717',
  phoneDisplay: '05-221-1717',
  phoneHref: 'tel:+88652211717',
  address: '嘉義縣民雄鄉大崎村內埔仔7之1號',
  addressEn: 'No. 7-1, Neipuzi, Dacun Village, Minxiong Township, Chiayi County, Taiwan',
  representative: '陳素貞',
  established: 1977,
  capital: 'NT$1,610,000',
  registrationNo: '99655111',
  trademark: '慶宗及圖 CHIN TZON',
  trademarkNo: '00234983',
  trademarkYear: 1984,
  website: 'https://qingzong-plastics.vercel.app',
  email: 'info@chintzon.com.tw',
  mapUrl: 'https://maps.google.com/?q=嘉義縣民雄鄉大崎村內埔仔7之1號',
  geo: {
    latitude: 23.5539,
    longitude: 120.4285,
  },
  businessHours: {
    weekday: '08:00 - 17:30',
    saturday: '08:00 - 12:00',
    sunday: '休息',
  },
  socialMedia: {
    facebook: 'https://www.facebook.com/慶宗塑膠',
  },
};

export const PRODUCTS = [
  {
    id: 'plastic-bags',
    name: '塑膠袋',
    nameEn: 'Plastic Bags',
    slug: 'plastic-bags',
    description: '各式PE/PP/OPP塑膠袋，包含背心袋、平口袋、夾鏈袋、食品袋等，支援客製化印刷。',
    shortDesc: '背心袋・平口袋・夾鏈袋・食品袋',
    icon: '🛍️',
    keywords: ['塑膠袋', 'PE袋', 'PP袋', '背心袋', '平口袋', '夾鏈袋'],
    priceRange: '依規格報價',
    image: '/images/plastic-bags.jpg',
  },
  {
    id: 'plastic-film',
    name: '塑膠膜',
    nameEn: 'Plastic Film',
    slug: 'plastic-film',
    description: 'PE膜、收縮膜、拉伸膜、農業用膜等，適用工業包裝、農業覆蓋、建材保護。',
    shortDesc: 'PE膜・收縮膜・拉伸膜・農業膜',
    icon: '📦',
    keywords: ['塑膠膜', 'PE膜', '收縮膜', '拉伸膜', '農業膜'],
    priceRange: '依規格報價',
    image: '/images/plastic-film.jpg',
  },
  {
    id: 'plastic-rope',
    name: '塑膠繩',
    nameEn: 'Plastic Rope',
    slug: 'plastic-rope',
    description: 'PP塑膠繩、打包繩、綑綁繩，高強度耐用，適用農業、漁業、物流包裝。',
    shortDesc: 'PP繩・打包繩・綑綁繩',
    icon: '🪢',
    keywords: ['塑膠繩', 'PP繩', '打包繩', '綑綁繩'],
    priceRange: '依規格報價',
    image: '/images/plastic-rope.jpg',
  },
  {
    id: 'plastic-net',
    name: '塑膠網',
    nameEn: 'Plastic Net',
    slug: 'plastic-net',
    description: '農業防蟲網、遮陽網、防鳥網、工地安全網等，多種規格可選。',
    shortDesc: '防蟲網・遮陽網・防鳥網・安全網',
    icon: '🕸️',
    keywords: ['塑膠網', '防蟲網', '遮陽網', '防鳥網', '安全網'],
    priceRange: '依規格報價',
    image: '/images/plastic-net.jpg',
  },
  {
    id: 'plastic-line',
    name: '塑膠線',
    nameEn: 'Plastic Line',
    slug: 'plastic-line',
    description: '各式塑膠線材、單絲線、編織線，適用農業綁紮、工業用途。',
    shortDesc: '單絲線・編織線・綁紮線',
    icon: '🧵',
    keywords: ['塑膠線', '單絲線', '編織線'],
    priceRange: '依規格報價',
    image: '/images/plastic-line.jpg',
  },
  {
    id: 'recycled-materials',
    name: '塑膠再製原料',
    nameEn: 'Recycled Plastic Materials',
    slug: 'recycled-materials',
    description: '塑膠再生粒、再製原料，響應循環經濟，提供高品質再生塑膠原料。',
    shortDesc: '再生粒・再製原料・循環經濟',
    icon: '♻️',
    keywords: ['塑膠再製原料', '再生塑膠', '塑膠回收', '循環經濟'],
    priceRange: '依規格報價',
    image: '/images/recycled-materials.jpg',
  },
  {
    id: 'custom-products',
    name: '客製化產品',
    nameEn: 'Custom Products',
    slug: 'custom-products',
    description: '依客戶需求客製化生產各式塑膠製品，提供印刷、特殊規格、專案開發等服務。',
    shortDesc: '客製印刷・特殊規格・專案開發',
    icon: '⚙️',
    keywords: ['客製化塑膠袋', '塑膠袋印刷', '客製塑膠製品'],
    priceRange: '依需求報價',
    image: '/images/custom-products.jpg',
  },
];

export const SERVICES = [
  {
    id: 'manufacturing',
    name: '塑膠製品製造',
    slug: 'manufacturing',
    description: '擁有完整生產線，從原料調配、吹膜、製袋到成品包裝，一條龍生產。',
    keywords: ['塑膠製品製造', '塑膠袋製造', '塑膠工廠'],
  },
  {
    id: 'oem',
    name: 'OEM代工服務',
    slug: 'oem-service',
    description: '接受品牌代工、大量訂單生產，嚴格品管確保品質一致。',
    keywords: ['塑膠袋代工', 'OEM代工', '塑膠代工廠'],
  },
  {
    id: 'custom-printing',
    name: '客製化印刷',
    slug: 'custom-printing',
    description: '提供單色至多色印刷服務，可印製LOGO、品牌名稱、產品資訊。',
    keywords: ['塑膠袋印刷', '客製化印刷', 'LOGO印刷'],
  },
  {
    id: 'wholesale',
    name: '批發供應',
    slug: 'wholesale',
    description: '長期穩定供貨，量大優惠，服務全台各地經銷商及企業客戶。',
    keywords: ['塑膠袋批發', '塑膠袋量販', '塑膠袋供應商'],
  },
  {
    id: 'recycling',
    name: '塑膠回收再製',
    slug: 'recycling',
    description: '響應環保政策，提供塑膠回收及再生原料製造服務。',
    keywords: ['塑膠回收', '塑膠再生', '循環經濟'],
  },
];

export const AREAS = [
  { id: 'chiayi', name: '嘉義縣市', slug: 'chiayi', description: '嘉義在地工廠，最快速的交貨與服務。' },
  { id: 'tainan', name: '台南市', slug: 'tainan', description: '服務台南地區，專人配送到府。' },
  { id: 'kaohsiung', name: '高雄市', slug: 'kaohsiung', description: '南部重要市場，穩定供貨。' },
  { id: 'pingtung', name: '屏東縣', slug: 'pingtung', description: '服務屏東農業及工業客戶。' },
  { id: 'yunlin', name: '雲林縣', slug: 'yunlin', description: '鄰近嘉義，快速供貨。' },
  { id: 'changhua', name: '彰化縣', slug: 'changhua', description: '中部地區重要客戶群。' },
  { id: 'taichung', name: '台中市', slug: 'taichung', description: '中部都會區，大量工業需求。' },
  { id: 'nantou', name: '南投縣', slug: 'nantou', description: '農業包裝需求，專業服務。' },
  { id: 'central-south', name: '中南部地區', slug: 'central-south', description: '全台中南部配送，物流完善。' },
  { id: 'nationwide', name: '全台服務', slug: 'nationwide', description: '大量訂單可配送全台，歡迎洽詢。' },
];

export const BLOG_CATEGORIES = [
  { id: 'plastic-knowledge', name: '塑膠知識', slug: 'plastic-knowledge', description: '塑膠材質、特性、應用知識' },
  { id: 'packaging-guide', name: '包裝指南', slug: 'packaging-guide', description: '包裝方案、材料選擇指南' },
  { id: 'industry-news', name: '產業動態', slug: 'industry-news', description: '塑膠產業趨勢與新聞' },
  { id: 'eco-friendly', name: '環保永續', slug: 'eco-friendly', description: '環保塑膠、循環經濟、ESG' },
  { id: 'product-application', name: '產品應用', slug: 'product-application', description: '各行業塑膠應用案例' },
  { id: 'food-packaging', name: '食品包裝', slug: 'food-packaging', description: '食品級塑膠袋、包裝法規' },
  { id: 'agriculture', name: '農業應用', slug: 'agriculture', description: '農業膜、防蟲網、覆蓋材料' },
  { id: 'industrial', name: '工業應用', slug: 'industrial', description: '工業包裝、物流包材' },
  { id: 'custom-printing', name: '客製印刷', slug: 'custom-printing', description: '印刷技術、設計建議' },
  { id: 'company-news', name: '公司動態', slug: 'company-news', description: '慶宗塑膠最新消息' },
];

export const NAV_ITEMS = [
  { label: '首頁', href: '/' },
  { label: '關於我們', href: '/about/' },
  {
    label: '產品中心',
    href: '/products/',
    children: PRODUCTS.map(p => ({ label: p.name, href: `/products/${p.slug}/` })),
  },
  {
    label: '服務項目',
    href: '/services/',
    children: SERVICES.map(s => ({ label: s.name, href: `/services/${s.slug}/` })),
  },
  { label: '案例展示', href: '/cases/' },
  { label: '知識專欄', href: '/blog/' },
  { label: '服務區域', href: '/areas/' },
  { label: '常見問答', href: '/faq/' },
  { label: '聯繫我們', href: '/contact/' },
];

export const SEO_KEYWORDS = {
  tier1: [
    '塑膠袋工廠', '塑膠袋批發', '客製化塑膠袋', 'PE袋製造', '塑膠膜工廠',
    '塑膠繩製造', '塑膠網工廠', '嘉義塑膠工廠', '塑膠袋代工', '塑膠袋印刷',
  ],
  tier2: [
    '背心袋批發', '夾鏈袋工廠', '食品袋製造', 'OPP袋批發', '收縮膜工廠',
    '拉伸膜批發', '農業用膜', '防蟲網批發', '打包繩工廠', '塑膠再生原料',
    '環保塑膠袋', '生物可分解袋', '塑膠袋客製印刷', '垃圾袋工廠', '快遞袋批發',
  ],
  tier3: [
    '嘉義塑膠袋批發', '台南塑膠袋工廠', '高雄塑膠袋批發', '南部塑膠代工',
    '塑膠袋價格', '塑膠袋最低訂購量', '塑膠袋印刷費用', '客製化包裝袋推薦',
    'PE袋和PP袋差別', '塑膠袋材質選擇', '食品級塑膠袋規範', '塑膠袋環保法規',
    '工業包裝袋推薦', '農業資材批發', '塑膠袋廠商推薦',
  ],
  tier4: [
    '塑膠袋', '包裝袋', '塑膠膜', '塑膠繩', '塑膠網',
    '客製化包裝', '包裝材料', '塑膠製品', '塑膠工廠', '包裝袋批發',
  ],
};
